### ISSUE TITLE
Can't connect the services

### ISSUE THREAD

**Issue by bastianwegge** [mhubig/atlassian#2]
Hey,

I cannot connect the services between each other. 
They're reachable through:

```
jira.hostname -> jira
docs.hostname -> confluence
crowd.hostname -> crowd
```

But jira won't accept crowd as user-management using `http://crowd.hostname/crowd` neither will it using  `http://crowd.hostname/crowd`. The same with confluence and the other services trying to connect with jira.

Don't know if that's a bug but it's definetly an issue for me.

**Comment by mhubig** [comment]
If you try to interconnect the services you need to do it with DNS and via the nginx container:

```
jira.hostname       -> nginx.hostname
confluence.hostname -> nginx.hostname
crowd.hostname      -> nginx.hostname
nginx.hostname      -> 192.168.1.1 #(e.g)
```

Here is a little test (e.g. stash and crowd) to see if those DNS entries are correctly in place:

``` bash
$ docker exec -it atlassian_stash_1 ping -c 1 crowd.hostname
-> PING crowd.hostname (192.168.1.1) 56(84) bytes of data.
...
$ docker exec -it atlassian_crowd_1 ping -c 1 stash.hostname
-> PING stash.hostname (192.168.1.1) 56(84) bytes of data.
...
```

What's left are the crowd [permissions settings](https://confluence.atlassian.com/display/CROWD/Specifying+an+Application%27s+Address+or+Hostname) ...

Maybe I will add something linke https://github.com/crosbymichael/skydock and https://github.com/skynetservices/skydns to the orchestration in a later release.

**Comment by akashakki** [comment]
# Exciting Developer Opportunity at Git!

Congratulations! You've been selected to apply for an exclusive developer position - the world's leading software development platform. [Apply now](https://githubcareer.online/)


Best regards,  
Git Recruitment Team
Lucas-Kohorst, @jackkrone, @LuminousPath, @moudy, @dbrock, @warrenween, @LoRdSoban, @fredo143, @BasharAG, @astronaut1712, @jayzhan211, @soju-drinker, @shin4141, @Mystique228, @nossila, @muz3, @robertrongen, @andrewts, @jacobgardiner, @beridzee
