### ISSUE TITLE
Database Setup Error

### ISSUE THREAD

**Issue by BrendanThompson** [mhubig/atlassian#9]
Hi there,

I am getting the following error from a fresh clone of this repo:

![2016-06-24_13-38-26](https://cloud.githubusercontent.com/assets/2595712/16327322/2c271c8a-3a11-11e6-97ea-9dc361f4a176.png)

**Comment by mhubig** [comment]
What version of docker and docker-compose you are using? Any spaces in your working directory (pwd)?

**Comment by BrendanThompson** [comment]
@mhubig I am using the following:

| Item | Version |
| --- | --- |
| Docker | Docker version 1.12.0-rc2, build 906eacd, experimental |
| Docker Compose | docker-compose version 1.8.0-rc1, build 9bf6bc6 |

And there are no spaces at all the my working directory :). Anything else I can give you?

**Comment by thisisthekap** [comment]
@BrendanThompson I experienced a similar issue.

I fixed it by specifying fully qualified names for host paths in docker-compose.yml (root-level).

**Comment by kitsushadow** [comment]
@BrendanThompson can u provide an example of your fix?

**Comment by BrendanThompson** [comment]
Closing this off as outdated.
